name: "terraform-deploy"
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
   
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6 # Altere para a versão desejada
   
      - name: Terraform Init
        run: terraform init
   
      - name: Terraform Plan
        run: terraform plan
        env:
          TF_CLI_ARGS: "-no-color"
   
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_CLI_ARGS: "-no-color"
   
      - name: Terraform Show
        run: terraform show
